import Image from 'next/image';
import Head from 'next/head';

const Layout = ({ children, title = 'World Ranks' }) => {
     // console.log('children', children.length)
     return (
          <div className="main-box h-screen font-poppins md:w-11/12 w-full mx-auto p-6">
               <Head>
                    <title>{title}</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="minimum-scale=1, initial-scale=1, width=device-width" />
                    <link rel="icon" href="/favicon.ico" />
               </Head>

               <header>
                    <div className="flex items-center justify-center">
                         <Image src="/favicon.ico" width={22} height={20} alt="" />
                         <h1 className="font-extrabold text-2xl ml-2"><span className="text-color">World</span> <span className="text-logo">Ranks</span></h1>
                    </div>
               </header>

               <main>
                    {children}
               </main>

               <footer className="text-color-secendary mt-12 flex justify-center text-xs">
                    nosirovabosjon3429@gmail.com
               </footer>

          </div>
     )
}

export default Layout;
